import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SavR - site Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero heading ='Save Money Easier' about='Make saving money easier with SavR'/>

      <Slider slides ={SliderData} />


    </div>
  );
}
